name: Gustave Paté's Hideout
tagline: Python, Linux, Stuff from outer space
pygments: true
timezone: Europe/Paris
author: Gustave Paté
motto: Human Abstraction Layer
email: gustave.pate / gmail
twitter: GustavePate
googleplus: gustave.pate
flattr: GustavePate
github: gustavepate
url: http://gustavepate.github.io
permalink: /blog/:year:month:day/:title/
