#!/bin/bash

# execute the following commands by hand if a proxy is needed
# then edit minimal.sh to add proxy setting before launching it
# way of doing it:
#  --proxy <[protocol://][user:password@]proxyhost[:port]>
# or -x http://proxy_server:proxy_port --proxy-user username:password


# get the full archive
#curl -#L https://raw.githubusercontent.com/GustavePate/dotfiles/master/minimal.sh -o ~/minimal.sh
curl -#L https://github.com/GustavePate/dotfiles/tarball/master -o ~/dot.tgz
# decompress it and execute
mkdir dot && tar -xzf ~/dot.tgz -C dot --strip-components 1 && rm ~/dot.tgz && chmod 764 ~/dot/minimal.sh && ~/dot/minimal.sh
